image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Clone Coreboot, build and install tools
    init: |
      git clone https://review.coreboot.org/coreboot
      cd coreboot 
      git submodule update --init --checkout
    command: gp sync-done clone && exit

  - name: Build tools
    init: gp sync-await clone
    command: |
      make -C ./coreboot/util/cbfstool cbfstool
      sudo make -C ./coreboot/util/cbfstool/ install
      make -C ./coreboot/util/ifdtool/
      sudo make -C ./coreboot/util/ifdtool/ install
      make -C ./coreboot iasl
      make -C ./coreboot nasm
      
      gp sync-done tools
      exit

  - name: Build crossgcc
    init: gp sync-await clone
    command: |
      make -C coreboot crossgcc-i386 CPUS=$(nproc)
      gp sync-done crossgcc
      exit

  - name: Build Coreboot
    init: |
      clear
      echo "We are cloning, building and installing required tools"
      echo "for coreboot_glk. This process will take quite a while"
      echo "even here on Gitpod. Please allow 10 - 15 minutes for"
      echo "this process to finish."
      gp sync-await clone
      echo "Cloning coreboot repo has finished"
      gp sync-await tools
      echo "Building the helper tools has finished"
      echo "We're building the crossgcc toolchain now. This is the"
      echo "big one that takes a while. BRB"
      gp sync-await crossgcc & ./spinner.sh $!
      exit
    command: bash build.sh


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8123
    onOpen: notify
  - port: 5000
    onOpen: open-preview
