image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: git clone https://review.coreboot.org/coreboot && cd coreboot && git submodule update --init --checkout
  - command: bash build.sh


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8123
    onOpen: notify
  - port: 5000
    onOpen: open-preview
