# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo "Installing Dependencies" && /workspace/coreboot_glk/startup.sh
  - command: echo "Setup has completed. To build for your device, run build.sh" && /workspace/coreboot_glk/build.sh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
